backend:
  name: github
  repo: CAN-Together/cape-town-together-website

display_url: https://capetowntogether.net
media_folder: src/static/assets/images/cms
public_folder: /assets/images/cms

collections:
  - name: pages
    label: Pages
    label_singular: page
    folder: src/data/pages
    extension: json
    create: true

    fields: 
      - name: title
        label: Title
        widget: string

      - name: url
        label: URL
        widget: string
        pattern: ['^\/.+', 'Must be relative to domain. (in other words it should start with an "/").']

      - name: icon
        label: Icon
        widget: select
        options:
          - hand 
          - clipboard
          - shield
          - facebook
          - pin
          - rocket
          - info

      - name: order
        label: Order
        widget: number
        comment: asdasd

      - name: body
        label: Content
        widget: markdown
        required: false

      - name: expanding
        label: Expanding Sections
        label_singular: expanding section
        widget: list
        default: []
        fields:

          - name: title
            label: Title
            widget: string
            default: ""

          - name: content
            label: Content
            widget: markdown
            default: ""