backend:
  name: github
  repo: CAN-Together/cape-town-together-website

display_url: https://capetowntogether.net
media_folder: src/static/assets/images/cms
public_folder: /assets/images/cms

collections:
  - name: general
    label: General
    extension: json
    files: 
      - name: homepage
        label: Homepage
        file: src/data/homepage.json
        fields:
          - name: sections
            label: Sections
            widget: list
            default: []
            hint: A collection of sections that contain buttons
            fields:

              - name: title
                label: Title
                hint: The title to show next to the icon for a specific section
                widget: string

              - name: icon
                label: Icon
                hint: The specific icon that should be used for a section
                widget: select
                options:
                  - hand 
                  - clipboard
                  - shield
                  - facebook
                  - pin
                  - rocket
                  - info

              - name: overview
                label: Overview
                hint: An optional sentence/paragraph that is show before buttons and/or widgets.
                widget: text
                required: false

              - name: type
                label: Type
                widget: select
                default: default
                hint: The type of section that should be used. All sections should be "default", with the exception of a single section that should be set to "embedded-search". The latter adds a widget above the buttons in a specified section that allows searching for a specific CAN. (Note that this will not reflect in the preview in the dashboard, but will be included in the actual site)
                options:
                  - default
                  - embedded-search

              - name: buttons
                label: Buttons
                hint: A collection of buttons (or a single button) that should be added to a section.
                widget: list
                default: []
                fields:
                  
                  - name: label
                    label: Label
                    widget: string
                    hint: The text to be displayed inside the button.

                  - name: url
                    label: URL
                    widget: string
                    hint: This is the link that users will be directed to when clicking the button.

                  - name: newTab
                    label: Opens new window
                    default: false
                    widget: boolean
                    hint: By default this is set to "false". However if you want a new window/tab to be opened in the browser when the link is clicked this can be set to true. It is recommended that this be set to true for links that navigate away from the capetowntogether.net website.
              
  - name: pages
    label: Pages
    label_singular: page
    folder: src/data/pages
    extension: json
    create: true

    fields: 
      - name: title
        label: Title
        widget: string
        hint: This is the text to be shown at the top of the page (as well as used when it is included in the menu)

      - name: url
        label: URL
        widget: string
        pattern: ['^\/.+', 'Must be relative to domain. (in other words it should start with an "/").']
        hint: This is the URL where the page will be located. For example "/example" will be mapped to "https://capetowntogether.net/example".

      - name: icon
        label: Icon
        widget: select
        hint: This the icon that will be used (from a pre-generated list of icons) next to the title at the top of the page
        options:
          - hand 
          - clipboard
          - shield
          - facebook
          - pin
          - rocket
          - info

      - name: order
        label: Order
        widget: number
        default: 0
        hint: If value is "0" then this page will not be listed in the website header menu. If another value it will be in the website header. The number assigned will determine the order in which page links appear in the menu. For example "1" will be ordered before "2" and other higher values. 

      - name: body
        label: Content
        widget: markdown
        required: false
        hint: This field is for optional (but is recommended to be included) introductory text content that should be shown before the expanding sections. Make sure that is always set to "rich text".

      - name: expanding
        label: Expandable Sections
        label_singular: expandable section
        hint: The following is a collection of expandable content areas that should go under the introduction content. Items can be added by pressing the "add expandable section" button and can be deleted by pressing the 'x' button on a specific section. Click on the ">" arrow to edit the details of associated with a specific expandable section.
        widget: list
        default: []
        fields:

          - name: title
            label: Title
            widget: string
            default: ""

          - name: content
            label: Content
            widget: markdown
            default: ""