backend:
  name: github
  repo: CAN-Together/cape-town-together-website

display_url: https://capetowntogether.net
media_folder: src/static/assets/images/cms
public_folder: /assets/images/cms

collections:
  - name: pages
    label: Pages
    folder: src/data/pages
    extension: json
    create: true

    fields: 
      - name: title
        label: Title
        widget: string

      - name: url
        label: URL
        widget: string

      - name: icon
        label: Icon
        widget: select
        options:
          - hand 
          - clipboard
          - shield
          - facebook
          - pin
          - rocket
          - info

      - name: order
        label: Order
        widget: number

      - name: body
        label: Content
        widget: markdown
        required: false

      - name: expanding
        label: Expanding Sections
        widget: list
        default: []
        fields:

          - name: title
            label: Title
            widget: string
            default: ""

          - name: content
            label: Content
            widget: markdown
            default: ""